# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt CLOBBER            # Don't care about overwrite existing file with > and >>.
                          # unset by modules/directory in prezto
unsetopt share_history    # Don't share history in multiple simutaneous zsh.
                          # set by modules/history in prezto


# No Ctrl+S freezing in vim.
stty -ixon

if [[ -n "${key[PageUp]}" ]]; then
  bindkey "${key[PageUp]}" backward-word
fi
if [[ -n "${key[PageDown]}" ]]; then
  bindkey "${key[PageDown]}" forward-word
fi

source ~/.dotfiles/zsh/alias.zsh
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/lazy.zsh

if [[ -f ~/.zshrc_local ]]; then
  source ~/.zshrc_local
fi
