# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt share_history

# No Ctrl+S freezing in vim.
stty -ixon

if [[ -n "${key[PageUp]}" ]]; then
  bindkey "${key[PageUp]}" backward-word
fi
if [[ -n "${key[PageDown]}" ]]; then
  bindkey "${key[PageDown]}" forward-word
fi

source ~/.dotfiles/zsh/alias.zsh
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/lazy.zsh

if [[ -f ~/.zshrc_local ]]; then
  source ~/.zshrc_local
fi

# Add completions to $fpath
fpath=("~/.dotfiles/completions" $fpath)
