[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "ruby"]

[settings.npm]
bun = true

[tools]
bat = "latest"
btop = "latest"
cosign = "latest"
dua = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
git-lfs = "latest"
jq = "latest"
jujutsu = "latest"
make = "latest"
neovim = "latest"
ripgrep = "latest"
shellcheck = "latest"
slsa-verifier = "latest"
usage = "latest"
zoxide = "latest"

[tools."github:Canop/broot"]
version = "latest"

[tools."github:Canop/broot".platforms]
linux-arm64 = { bin_path = "aarch64-unknown-linux-gnu" }
linux-x64 = { bin_path = "x86_64-unknown-linux-gnu" }
macos-arm64 = { bin_path = "aarch64-apple-darwin" }
